### ISSUE TITLE
TypeError: Cannot read property 'visitClass' of undefined

### ISSUE THREAD

**Issue by ArxdSilva** [henriquea/webpack-react-starter#3]
I had this issue while I tried to run "npm run build":

> webpack-react-starter@0.1.0 build /Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master
> ./scripts/build

TypeError: Cannot read property 'visitClass' of undefined
    at monkeypatch (/Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/babel-eslint/index.js:199:40)
    at Object.exports.parse (/Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/babel-eslint/index.js:410:5)
    at parse (/Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/eslint/lib/eslint.js:453:27)
    at EventEmitter.module.exports.api.verify (/Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/eslint/lib/eslint.js:607:15)
    at processText (/Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/eslint/lib/cli-engine.js:201:27)
    at CLIEngine.executeOnText (/Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/eslint/lib/cli-engine.js:361:26)
    at lint (/Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/eslint-loader/index.js:26:20)
    at Object.module.exports (/Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/eslint-loader/index.js:120:7)
    at WEBPACK_CORE_LOADER_EXECUTION (/Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
    at runSyncOrAsync (/Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
    at nextLoader (/Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
TypeError: Cannot read property 'visitClass' of undefined
    at monkeypatch (/Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/babel-eslint/index.js:199:40)
    at Object.exports.parse (/Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/babel-eslint/index.js:410:5)
    at parse (/Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/eslint/lib/eslint.js:453:27)
    at EventEmitter.module.exports.api.verify (/Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/eslint/lib/eslint.js:607:15)
    at processText (/Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/eslint/lib/cli-engine.js:201:27)
    at CLIEngine.executeOnText (/Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/eslint/lib/cli-engine.js:361:26)
    at lint (/Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/eslint-loader/index.js:26:20)
    at Object.module.exports (/Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/eslint-loader/index.js:120:7)
    at WEBPACK_CORE_LOADER_EXECUTION (/Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
    at runSyncOrAsync (/Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
    at nextLoader (/Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! webpack-react-starter@0.1.0 build: `./scripts/build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack-react-starter@0.1.0 build script './scripts/build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webpack-react-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./scripts/build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webpack-react-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webpack-react-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/arthu.rsilva/GitHub/ReactJS/webpack-react-starter-master/npm-debug.log

To solve it and make it work I had to delete the .eslintrc file and comment the preloaders inside the modules in webpack.config.js file.

**Comment by henriquea** [comment]
Hi @ArxdSilva. Tranquilo? Então brother eu não estou usando mais este repo pela velocidade que as coisas tem se atualizado. Não consegui mais manter o peace. Estou usando https://github.com/gaearon/react-transform-boilerplate quando preciso de um boilerplate.

**Comment by aspic** [comment]
https://github.com/babel/babel-eslint/issues/243 -- this resolved the issue for me. Basically removing escope, and then 'downgrade' to an earlier version: npm install --save-dev escope@3.3.0

**Comment by henriquea** [comment]
Thanks @aspic!
